"""
Prometheus metrics for the inference API.

Three categories:
  1. Auto-instrumented request metrics (latency histogram, error rates) —
     handled by prometheus-fastapi-instrumentator, wired in inference/api.py.
  2. Auth rejection counters — incremented in inference/auth.py.
  3. Model quality/staleness gauges — updated on every /metrics scrape
     so Grafana alerts reflect the actual current state, not just startup.

Scraped by default at GET /metrics (same port as the API).
In production, consider:
  - Restricting /metrics via network policy or a sidecar proxy, since it
    exposes internal model metrics you may not want public.
  - Moving to a separate port via a second uvicorn worker if you need
    strict traffic separation between the API and the scrape endpoint.
"""
from __future__ import annotations

from prometheus_client import Counter, Gauge

# ---- Auth -------------------------------------------------------------- #
auth_rejections = Counter(
    "pci_auth_rejections_total",
    "Total API key authentication rejections.",
    ["reason"],   # label values: "missing_key" | "invalid_key"
)

# ---- Model quality / staleness ----------------------------------------- #
artifact_age_seconds = Gauge(
    "pci_artifact_age_seconds",
    "Seconds since the currently-served model was generated by the training pipeline. "
    "Alert if this exceeds your expected training cadence (e.g. > 48h).",
)

model_mae = Gauge(
    "pci_model_mae",
    "Mean Absolute Error (violations/hr) of the currently-serving forecast model. "
    "Alert if this rises significantly above your baseline.",
)

active_hotspots = Gauge(
    "pci_active_hotspots_total",
    "Number of active hotspot clusters in the currently-serving model.",
)


def update_from_metrics_dict(metrics_dict: dict) -> None:
    """Refresh all model-quality gauges from a metrics.json payload.
    Called in the /metrics scrape middleware so values stay current."""
    from datetime import datetime, timezone  # local import — avoids pulling stdlib into module load

    mae = metrics_dict.get("forecast_mae")
    if mae is not None:
        model_mae.set(float(mae))

    total = metrics_dict.get("total_hotspots")
    if total is not None:
        active_hotspots.set(int(total))

    generated_at = metrics_dict.get("generated_at")
    if generated_at:
        try:
            dt = datetime.fromisoformat(generated_at)
            age = (datetime.now(timezone.utc) - dt).total_seconds()
            artifact_age_seconds.set(max(0.0, age))
        except (ValueError, TypeError):
            pass
